version: "3.8"
services:
  db:
    container_name: "${DB_CONTAINER_ID}"
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data_ac_cluster:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root!238Ji*"
      POSTGRES_DB: "astrocluster"

  clusterservice:
    container_name: "${CLUSTER_SERVICE_CONTAINER_ID}"
    build:
      context: ./cluster
      dockerfile: Dockerfile
      args:
        GENERATE_GRPC: "${GENERATE_GRPC}"
    ports:
      - "50051:50051"
    volumes:
      - shared_cloned_projects:/ac-clustering-service/projects

  server:
    container_name: "${SERVER_CONTAINER_ID}"
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MAVEN_PROFILES: "${MAVEN_PROFILES}"
        BE_GRPC_DOCKER_PATH: "${BE_GRPC_DOCKER_PATH}"
    ports:
      - "8080:8080"
    volumes:
      - shared_cloned_projects:/ac-server/projects
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/astrocluster"
      BE_GRPC_DOCKER_PATH: "${BE_GRPC_DOCKER_PATH}"

  client:
    container_name: "${CLIENT_CONTAINER_ID}"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

volumes:
  pg_data_ac_cluster:
    name: "pg_data_ac_cluster"
  shared_cloned_projects:
    name: "shared_cloned_projects"
