// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cluster.proto
// Protobuf Java Version: 4.27.2

package edu.setokk.astrocluster.grpc;

public final class ClusterStubGrpc {
  private ClusterStubGrpc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ClusterStubGrpc.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cluster_proto_ClusterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cluster_proto_ClusterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cluster_proto_ClusterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cluster_proto_ClusterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcluster.proto\022\rcluster.proto\"@\n\016Cluste" +
      "rRequest\022\014\n\004path\030\001 \001(\t\022\014\n\004lang\030\002 \001(\t\022\022\n\n" +
      "extensions\030\003 \003(\t\";\n\017ClusterResponse\022\025\n\rc" +
      "lusterLabels\030\001 \003(\003\022\021\n\tfilePaths\030\002 \003(\t2d\n" +
      "\016ClusterService\022R\n\021PerformClustering\022\035.c" +
      "luster.proto.ClusterRequest\032\036.cluster.pr" +
      "oto.ClusterResponseB1\n\034edu.setokk.astroc" +
      "luster.grpcB\017ClusterStubGrpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cluster_proto_ClusterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cluster_proto_ClusterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cluster_proto_ClusterRequest_descriptor,
        new java.lang.String[] { "Path", "Lang", "Extensions", });
    internal_static_cluster_proto_ClusterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cluster_proto_ClusterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cluster_proto_ClusterResponse_descriptor,
        new java.lang.String[] { "ClusterLabels", "FilePaths", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
