// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cluster.proto
// Protobuf Java Version: 4.27.2

package edu.setokk.astrocluster.cluster.proto;

public interface ClusterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cluster.proto.ClusterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string lang = 2;</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 2;</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>repeated string extensions = 3;</code>
   * @return A list containing the extensions.
   */
  java.util.List<java.lang.String>
      getExtensionsList();
  /**
   * <code>repeated string extensions = 3;</code>
   * @return The count of extensions.
   */
  int getExtensionsCount();
  /**
   * <code>repeated string extensions = 3;</code>
   * @param index The index of the element to return.
   * @return The extensions at the given index.
   */
  java.lang.String getExtensions(int index);
  /**
   * <code>repeated string extensions = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the extensions at the given index.
   */
  com.google.protobuf.ByteString
      getExtensionsBytes(int index);
}
