// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cluster.proto
// Protobuf Java Version: 4.27.2

package edu.setokk.astrocluster.cluster.proto;

/**
 * Protobuf type {@code cluster.proto.ClusterRequest}
 */
public final class ClusterRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cluster.proto.ClusterRequest)
    ClusterRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ClusterRequest.class.getName());
  }
  // Use ClusterRequest.newBuilder() to construct.
  private ClusterRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClusterRequest() {
    path_ = "";
    lang_ = "";
    extensions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.setokk.astrocluster.cluster.proto.ClusterStubGrpc.internal_static_cluster_proto_ClusterRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.setokk.astrocluster.cluster.proto.ClusterStubGrpc.internal_static_cluster_proto_ClusterRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.setokk.astrocluster.cluster.proto.ClusterRequest.class, edu.setokk.astrocluster.cluster.proto.ClusterRequest.Builder.class);
  }

  public static final int PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object path_ = "";
  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lang_ = "";
  /**
   * <code>string lang = 2;</code>
   * @return The lang.
   */
  @java.lang.Override
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lang_ = s;
      return s;
    }
  }
  /**
   * <code>string lang = 2;</code>
   * @return The bytes for lang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList extensions_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string extensions = 3;</code>
   * @return A list containing the extensions.
   */
  public com.google.protobuf.ProtocolStringList
      getExtensionsList() {
    return extensions_;
  }
  /**
   * <code>repeated string extensions = 3;</code>
   * @return The count of extensions.
   */
  public int getExtensionsCount() {
    return extensions_.size();
  }
  /**
   * <code>repeated string extensions = 3;</code>
   * @param index The index of the element to return.
   * @return The extensions at the given index.
   */
  public java.lang.String getExtensions(int index) {
    return extensions_.get(index);
  }
  /**
   * <code>repeated string extensions = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the extensions at the given index.
   */
  public com.google.protobuf.ByteString
      getExtensionsBytes(int index) {
    return extensions_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(path_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, path_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, lang_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, extensions_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(path_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, path_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lang_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < extensions_.size(); i++) {
        dataSize += computeStringSizeNoTag(extensions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getExtensionsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.setokk.astrocluster.cluster.proto.ClusterRequest)) {
      return super.equals(obj);
    }
    edu.setokk.astrocluster.cluster.proto.ClusterRequest other = (edu.setokk.astrocluster.cluster.proto.ClusterRequest) obj;

    if (!getPath()
        .equals(other.getPath())) return false;
    if (!getLang()
        .equals(other.getLang())) return false;
    if (!getExtensionsList()
        .equals(other.getExtensionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + getLang().hashCode();
    if (getExtensionsCount() > 0) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.setokk.astrocluster.cluster.proto.ClusterRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cluster.proto.ClusterRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cluster.proto.ClusterRequest)
      edu.setokk.astrocluster.cluster.proto.ClusterRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.setokk.astrocluster.cluster.proto.ClusterStubGrpc.internal_static_cluster_proto_ClusterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.setokk.astrocluster.cluster.proto.ClusterStubGrpc.internal_static_cluster_proto_ClusterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.setokk.astrocluster.cluster.proto.ClusterRequest.class, edu.setokk.astrocluster.cluster.proto.ClusterRequest.Builder.class);
    }

    // Construct using edu.setokk.astrocluster.cluster.proto.ClusterRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      path_ = "";
      lang_ = "";
      extensions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.setokk.astrocluster.cluster.proto.ClusterStubGrpc.internal_static_cluster_proto_ClusterRequest_descriptor;
    }

    @java.lang.Override
    public edu.setokk.astrocluster.cluster.proto.ClusterRequest getDefaultInstanceForType() {
      return edu.setokk.astrocluster.cluster.proto.ClusterRequest.getDefaultInstance();
    }

    @java.lang.Override
    public edu.setokk.astrocluster.cluster.proto.ClusterRequest build() {
      edu.setokk.astrocluster.cluster.proto.ClusterRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.setokk.astrocluster.cluster.proto.ClusterRequest buildPartial() {
      edu.setokk.astrocluster.cluster.proto.ClusterRequest result = new edu.setokk.astrocluster.cluster.proto.ClusterRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(edu.setokk.astrocluster.cluster.proto.ClusterRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.path_ = path_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lang_ = lang_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        extensions_.makeImmutable();
        result.extensions_ = extensions_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.setokk.astrocluster.cluster.proto.ClusterRequest) {
        return mergeFrom((edu.setokk.astrocluster.cluster.proto.ClusterRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.setokk.astrocluster.cluster.proto.ClusterRequest other) {
      if (other == edu.setokk.astrocluster.cluster.proto.ClusterRequest.getDefaultInstance()) return this;
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLang().isEmpty()) {
        lang_ = other.lang_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.extensions_.isEmpty()) {
        if (extensions_.isEmpty()) {
          extensions_ = other.extensions_;
          bitField0_ |= 0x00000004;
        } else {
          ensureExtensionsIsMutable();
          extensions_.addAll(other.extensions_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              path_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              lang_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureExtensionsIsMutable();
              extensions_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object path_ = "";
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      path_ = getDefaultInstance().getPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1;</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object lang_ = "";
    /**
     * <code>string lang = 2;</code>
     * @return The lang.
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lang = 2;</code>
     * @return The bytes for lang.
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lang = 2;</code>
     * @param value The lang to set.
     * @return This builder for chaining.
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lang_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLang() {
      lang_ = getDefaultInstance().getLang();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 2;</code>
     * @param value The bytes for lang to set.
     * @return This builder for chaining.
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lang_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList extensions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureExtensionsIsMutable() {
      if (!extensions_.isModifiable()) {
        extensions_ = new com.google.protobuf.LazyStringArrayList(extensions_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @return A list containing the extensions.
     */
    public com.google.protobuf.ProtocolStringList
        getExtensionsList() {
      extensions_.makeImmutable();
      return extensions_;
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @return The count of extensions.
     */
    public int getExtensionsCount() {
      return extensions_.size();
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @param index The index of the element to return.
     * @return The extensions at the given index.
     */
    public java.lang.String getExtensions(int index) {
      return extensions_.get(index);
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the extensions at the given index.
     */
    public com.google.protobuf.ByteString
        getExtensionsBytes(int index) {
      return extensions_.getByteString(index);
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @param index The index to set the value at.
     * @param value The extensions to set.
     * @return This builder for chaining.
     */
    public Builder setExtensions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureExtensionsIsMutable();
      extensions_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @param value The extensions to add.
     * @return This builder for chaining.
     */
    public Builder addExtensions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureExtensionsIsMutable();
      extensions_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @param values The extensions to add.
     * @return This builder for chaining.
     */
    public Builder addAllExtensions(
        java.lang.Iterable<java.lang.String> values) {
      ensureExtensionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, extensions_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtensions() {
      extensions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string extensions = 3;</code>
     * @param value The bytes of the extensions to add.
     * @return This builder for chaining.
     */
    public Builder addExtensionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureExtensionsIsMutable();
      extensions_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:cluster.proto.ClusterRequest)
  }

  // @@protoc_insertion_point(class_scope:cluster.proto.ClusterRequest)
  private static final edu.setokk.astrocluster.cluster.proto.ClusterRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.setokk.astrocluster.cluster.proto.ClusterRequest();
  }

  public static edu.setokk.astrocluster.cluster.proto.ClusterRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClusterRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClusterRequest>() {
    @java.lang.Override
    public ClusterRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClusterRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClusterRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.setokk.astrocluster.cluster.proto.ClusterRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

